//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.261
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlayPcmWin.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlayPcmWin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sorry... Please stop playback to add files to the playlist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CannotAddFile {
            get {
                return ResourceManager.GetString("CannotAddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reading files... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ChangingPlayGroup {
            get {
                return ResourceManager.GetString("ChangingPlayGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clipped sample value detected on floating point PCM data!
        ///  Clipped sample value count={1}, FileName={0}
        /// に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ClippedSampleDetected {
            get {
                return ResourceManager.GetString("ClippedSampleDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CUE files|*.cue に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string CueFileFilter {
            get {
                return ResourceManager.GetString("CueFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DeviceStateChanged. DeviceId={0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DeviceStateChanged {
            get {
                return ResourceManager.GetString("DeviceStateChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error code に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ErrorCode {
            get {
                return ResourceManager.GetString("ErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Event driven に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EventDriven {
            get {
                return ResourceManager.GetString("EventDriven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exclusive に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Exclusive {
            get {
                return ResourceManager.GetString("Exclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   floating point numbers に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string FloatingPointNumbers {
            get {
                return ResourceManager.GetString("FloatingPointNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Latency に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Latency {
            get {
                return ResourceManager.GetString("Latency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PlayPcmWin uses libFLAC.
        ///libFLAC license is a New BSD License. libFlacLicense.txt on the PlayPcmWin.exe folder contains full text of license.
        ///
        ///PlayPcmWin uses Jcode.pm character encoding detect function.
        ///Jcode.pm copyright is as follows: Copyright 1999-2005 Dan Kogai に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LicenseText {
            get {
                return ResourceManager.GetString("LicenseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Memory exhausted. Please reduce files on playlist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MemoryExhausted {
            get {
                return ResourceManager.GetString("MemoryExhausted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Nothing to store  に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NothingToStore {
            get {
                return ResourceManager.GetString("NothingToStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not supported file format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotSupportedFileFormat {
            get {
                return ResourceManager.GetString("NotSupportedFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Not supported quantization bit rate. supported formats are 16, 24 and 32 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NotSupportedQuantizationBitRate {
            get {
                return ResourceManager.GetString("NotSupportedQuantizationBitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pa_use に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Paused に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Paused {
            get {
                return ResourceManager.GetString("Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play completed. elapsed time is に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PlayCompletedElapsedTimeIs {
            get {
                return ResourceManager.GetString("PlayCompletedElapsedTimeIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Playing. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Playing {
            get {
                return ResourceManager.GetString("Playing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All tracks に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PlayModeAllTracks {
            get {
                return ResourceManager.GetString("PlayModeAllTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   All tracks repeat に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PlayModeAllTracksRepeat {
            get {
                return ResourceManager.GetString("PlayModeAllTracksRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   One track に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PlayModeOneTrack {
            get {
                return ResourceManager.GetString("PlayModeOneTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   One track repeat に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PlayModeOneTrackRepeat {
            get {
                return ResourceManager.GetString("PlayModeOneTrackRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shuffle に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PlayModeShuffle {
            get {
                return ResourceManager.GetString("PlayModeShuffle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shuffle repeat に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PlayModeShuffleRepeat {
            get {
                return ResourceManager.GetString("PlayModeShuffleRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Play start failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PlayStartFailed {
            get {
                return ResourceManager.GetString("PlayStartFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please create the playlist. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PleaseCreatePlaylist {
            get {
                return ResourceManager.GetString("PleaseCreatePlaylist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PPWPL files|*.ppwpl に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PpwplFileFilter {
            get {
                return ResourceManager.GetString("PpwplFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Add more files to the playlist or Press play button に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PressPlayButton {
            get {
                return ResourceManager.GetString("PressPlayButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Read completed. ready to play. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReadCompleted {
            get {
                return ResourceManager.GetString("ReadCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Read error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReadError {
            get {
                return ResourceManager.GetString("ReadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Read failed files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReadFailedFiles {
            get {
                return ResourceManager.GetString("ReadFailedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Read {0} file failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReadFileFailed {
            get {
                return ResourceManager.GetString("ReadFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setup device completed. Now reading files to main memory... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReadingFiles {
            get {
                return ResourceManager.GetString("ReadingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Read playgroup {0} completed. Elapsed time: {1}ms に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ReadPlayGroupNCompleted {
            get {
                return ResourceManager.GetString("ReadPlayGroupNCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Missing files while restoring playlist に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RestoreFailedFiles {
            get {
                return ResourceManager.GetString("RestoreFailedFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Resume(_U) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save file failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SaveFileFailed {
            get {
                return ResourceManager.GetString("SaveFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   *Please confirm sample rate or quantization bit rate are supported on your device using &quot;list supported format&quot; feature. Press [Clear the playlist][List supported format]
        ///*Some professional audio devices (RME Fireface, M-Audio ProFire, Echo AudioFire etc.) are not able to be changed master sampling rate via WASAPI. Please use Fireface settings, M-Audio Profire control panel or equivallent tools on your system tray to change master sampling rate of those devices before playback.
        ///*44.1kHz and 88.2kHz sample [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SetupFailAdvice {
            get {
                return ResourceManager.GetString("SetupFailAdvice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shared に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Shared {
            get {
                return ResourceManager.GetString("Shared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stopping... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Stopping {
            get {
                return ResourceManager.GetString("Stopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Supported files|*.wav;*.wave;*.flac;*.aif;*.aiff;*.cue;*.ppwpl|WAVE files|*.wav;*.wave|FLAC files|*.flac|AIFF files|*.aif;*.aiff|CUE files|*.cue|PPWPL files|*.ppwpl|All files|*.* に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SupportedFileFilter {
            get {
                return ResourceManager.GetString("SupportedFileFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Timer driven に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TimerDriven {
            get {
                return ResourceManager.GetString("TimerDriven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This file contains Too many channels(&gt;31) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TooManyChannels {
            get {
                return ResourceManager.GetString("TooManyChannels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unexpected end of stream. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UnexpectedEndOfStream {
            get {
                return ResourceManager.GetString("UnexpectedEndOfStream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Using device state change detected! DeviceName={0} DeviceId={1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UsingDeviceStateChanged {
            get {
                return ResourceManager.GetString("UsingDeviceStateChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Valid bits に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ValidBits {
            get {
                return ResourceManager.GetString("ValidBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Version に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
    }
}
