//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.296
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BpsConvWin.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BpsConvWin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Convert completed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConvertEnd {
            get {
                return ResourceManager.GetString("ConvertEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Converting: {0} ==&gt; {1} ({2}bps) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConvertingProgressText {
            get {
                return ResourceManager.GetString("ConvertingProgressText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Conversion failed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConvFailedByExcepetion {
            get {
                return ResourceManager.GetString("ConvFailedByExcepetion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Conversion failed. please specify 16bit or 24bit PCM RIFF WAV file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ConvFailedByWrongFormat {
            get {
                return ResourceManager.GetString("ConvFailedByWrongFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Now converting... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NowConverting {
            get {
                return ResourceManager.GetString("NowConverting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output file name: {0} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string OutputFileNameGuideText {
            get {
                return ResourceManager.GetString("OutputFileNameGuideText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Press [Browse..] button and select wav file to input に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PleasePressBrowseButton {
            get {
                return ResourceManager.GetString("PleasePressBrowseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please press [start convert] button に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PleasePressConvButton {
            get {
                return ResourceManager.GetString("PleasePressConvButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WAV files (*.wav)|*.wav に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string WavFileFilter {
            get {
                return ResourceManager.GetString("WavFileFilter", resourceCulture);
            }
        }
    }
}
